AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3bucketName:
    Type: String
    Default: "eeny-2025"
  DeployName:
    Type: String
    Default: "Eeny2025"

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DeployName}-lambda"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${DeployName}lambda"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action: dynamodb:*
                Resource: "*"

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${DeployName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH

  FetchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${DeployName}"
      Runtime: python3.13
      Handler: "eeny.lambda_handler"
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Sub "${S3bucketName}"
        S3Key: "eeny.zip"
      MemorySize: 256
      Environment:
        Variables:
          BUCKET_NAME: !Sub "${S3bucketName}"

  FetchFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt FetchFunction.Arn

  SNSHealthTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AWSHealthNotifications

  SNSHealthSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSHealthTopic
      Protocol: email
      Endpoint: "your-email@example.com"  # Change to your email

  SNSHealthPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSHealthTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: health.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref SNSHealthTopic

  EventBridgeHealthRule:
    Type: AWS::Events::Rule
    Properties:
      Name: AWSHealthDynamoDBAlerts
      EventPattern:
        source:
          - "aws.health"
        detail-type:
          - "AWS Health Event"
        detail:
          service:
            - "DynamoDB"
          region:
            - "${AWS::REGION}"
      State: ENABLED
      Targets:
        - Id: "1"
          Arn: !Ref SNSHealthTopic

Outputs:
  FetchFunctionUrl:
    Description: "The URL of the Lambda function"
    Value: !GetAtt FetchFunctionUrl.FunctionUrl
    Export:
      Name: !Sub "${DeployName}-FetchFunctionUrl"
  SNSHealthTopicArn:
    Description: "SNS Topic ARN for AWS Health Notifications"
    Value: !Ref SNSHealthTopic
